// <auto-generated/>
namespace Demo;
public static class IconFontProviderBuilder{
///<summary>
///帮助
///</summary>
public const string Help = "\ue623";

///<summary>
///ReDo
///</summary>
public const string ReDo = "\ue7fa";

///<summary>
///UnDo
///</summary>
public const string UnDo = "\ue842";

///<summary>
///收藏
///</summary>
public const string Favourite = "\ue78f";

///<summary>
///版本管理
///</summary>
public const string Versionmanage = "\ue653";

///<summary>
///锁定
///</summary>
public const string Lock = "\ue7fb";

///<summary>
///导入
///</summary>
public const string Import = "\ue977";

///<summary>
///导出
///</summary>
public const string Export = "\ue60b";

///<summary>
///MarkDown
///</summary>
public const string MarkDown = "\ue72c";

///<summary>
///pdf
///</summary>
public const string PDF = "\ue759";

///<summary>
///Txt
///</summary>
public const string Txt = "\ue7b0";

///<summary>
///Word
///</summary>
public const string Word = "\ue665";

///<summary>
///points
///</summary>
public const string points = "\ue626";

///<summary>
///添加
///</summary>
public const string Add = "\ue69f";

///<summary>
///setting
///</summary>
public const string Setting = "\ue78e";

///<summary>
///macos-minimize
///</summary>
public const string MacosMinimize = "\ue6ae";

///<summary>
///macos-maximize
///</summary>
public const string MacosMaximize = "\ue6c7";

///<summary>
///macos-close
///</summary>
public const string MacosClose = "\ue6c8";

///<summary>
///今天
///</summary>
public const string Today = "\ue8cf";

///<summary>
///所有
///</summary>
public const string All = "\ue62c";

///<summary>
///左侧边栏
///</summary>
public const string LeftSliderBar = "\ue60e";

///<summary>
///查看
///</summary>
public const string Eye = "\ue7ed";

///<summary>
///选项
///</summary>
public const string Options = "\ue636";

///<summary>
///回收站
///</summary>
public const string Trash = "\ue654";

///<summary>
///同步失败
///</summary>
public const string SyncError = "\ue600";

///<summary>
///共享
///</summary>
public const string Share = "\ue6ee";

///<summary>
///同步
///</summary>
public const string Sync = "\ue6ca";

///<summary>
///固定
///</summary>
public const string Pin = "\ue67b";

///<summary>
///readonly
///</summary>
public const string UnReadable = "\ue673";

///<summary>
///取消固定
///</summary>
public const string UnPin = "\ueb02";

///<summary>
///创建新文件夹
///</summary>
public const string NewFolder = "\ue82d";

}
